solution for buttons in task 3
js-tasks-ru/htmlcss-20220616_xenia-klyukina pull request #4
Opened 2022-06-22 13:31 UTC by klyukinaxen

2022-06-22 13:31 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-06-22 22:13 UTC, GSemikozov requested changes

2022-06-22 22:13 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    width: 185px;
не стоит жестко фиксировать размер кнопки - пусть растягивается по своему содержимому

2022-06-22 22:13 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    height: 50px;
высота не по дизайну)

2022-06-22 22:13 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    color: white;
цвета проставляем из переменных

2022-06-22 22:13 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    font-size: 16px;
не хватает font-family + padding

2022-06-22 22:13 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    margin: 20px 0 20px 15px;
марджины на уровне блока ни в коем случае не задаем

2022-06-24 15:49 UTC, klyukinaxen commented on 03-lection1/01-button/button.css
> +    margin: 20px 0 20px 15px;
тогда их нужно задавать на уровне самой кнопки?
или создавать отдельный контейнер и у него задавать отступы? в таком случае я не очень понимаю как сделать отступы между кнопками так, чтобы не было лишних

2022-06-24 15:57 UTC, klyukinaxen commented on 03-lection1/01-button/button.css
> +    width: 185px;
но тогда все кнопки будут разного размера, потому что у каждой кнопки разный размер содержимого?

2022-06-24 15:59 UTC, klyukinaxen commented on 03-lection1/01-button/button.css
> +    font-size: 16px;
а для чего здесь будет нужен padding?

2022-06-24 19:12 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    width: 185px;
да, верно)
если хотим растягивать по родителю на 100% - тогда добавляем модификатор например `.button_full_width { width: 100% }`

2022-06-24 19:13 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    font-size: 16px;
не не фиксируем ширину (а мы договорились не фиксировать), то текст по-любому будет прилипать к границам кнопки

2022-06-24 19:15 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    margin: 20px 0 20px 15px;
нет, кнопка - это и есть уровень блока .button) Задавать как вариант через классы-миксы в контексте того блока куда встраиваемся, но - в дайнный момент мы никуда не встраиваемся, просто размещаем кнопки на уровне body.
в данной задаче вообще не стоит заморачиваться с отступами / вариантом размещения кнопок по сетке.

2022-06-27 14:45 UTC, GSemikozov requested changes

2022-06-27 14:45 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    background-color: white;
в этом типе кнопки по-прежнему не используем css-переменные)

2022-06-28 19:31 UTC, GSemikozov approved these changes

2022-06-28 19:32 UTC, merged