add solution for task 3 - accordion
js-tasks-ru/htmlcss-20220616_xenia-klyukina pull request #5
Opened 2022-06-22 16:15 UTC by klyukinaxen

2022-06-22 16:16 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-06-23 14:43 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-07-05 10:58 UTC, GSemikozov requested changes

2022-07-05 10:58 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +@import '../../assets/fonts/fonts.css';
не нужно импортировать глобальные стили в файлы стилей компонента - они ведь глобальные)

2022-07-05 10:58 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +body {
это нужно определить глобально для всего проекта? если да - то в main.css. Если только для данного блока - то перенести в .accordion

2022-07-05 10:58 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.main {
нельзя описывать одни блоки в других. Если это глобальная настройка для блока - то там и надо добавить)

2022-07-05 10:58 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin-top: 10px;
на уровне блока марджины не задаем.

2022-07-05 10:58 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    width: 730px;
жестко ширину не фиксируем

2022-07-05 10:58 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding: 20px 0 20px 30px;
точно совпадает с дизайном?

2022-07-05 10:58 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion .accordion__summary {
в этой строке .accordion не нужно, лишняя вложенность

2022-07-05 10:58 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin: 16px 20px;
вот здесь margin-top еще может быть, но в остальном - эти отступы кажутся лишними (должны быть общие паддинги на уровне accordion__details)

2022-07-05 10:58 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__details.first[open] {
отсюда и ниже - удалим)

2022-07-10 09:30 UTC, GSemikozov approved these changes

2022-07-10 09:30 UTC, merged