Semantic layout
js-tasks-ru/htmlcss-20220616_xenia-klyukina pull request #6
Opened 2022-06-24 15:38 UTC by klyukinaxen

2022-06-24 15:41 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-24 15:42 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-24 19:16 UTC, GSemikozov requested changes

2022-06-24 19:16 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +@import url('https://fonts.googleapis.com/css2?family=Inter:wght@200;400;600&display=swap');
ой.. это точно здесь решение аккордиона?

2022-06-27 12:49 UTC, klyukinaxen commented on 03-lection1/02-accordion/accordion.css
> +@import url('https://fonts.googleapis.com/css2?family=Inter:wght@200;400;600&display=swap');
упс
а что нужно делать, когда в коммит попали изменения с другого задания?
как это вообще можно поправить и можно ли?

2022-06-27 14:46 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +@import url('https://fonts.googleapis.com/css2?family=Inter:wght@200;400;600&display=swap');
в текущей ситуации подождать пока замерджим предыдущим, и потом подольем обновленный апстрим мастер

2022-07-05 10:59 UTC, GSemikozov approved these changes

2022-07-05 10:59 UTC, merged