add solution for task histogram
js-tasks-ru/htmlcss-20220616_xenia-klyukina pull request #7
Opened 2022-06-27 15:26 UTC by klyukinaxen

2022-06-27 15:40 UTC, GSemikozov requested changes

2022-06-27 15:40 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +@import '../../assets/fonts/fonts.css';
не нужно, мы их (шрифты) глобально подключаем через main.css

2022-06-27 15:40 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: 354px;
ширину не ограничиваем

2022-06-27 15:40 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.top-part {
если это не отдельный блок, а элемент блока - тогда .histogram__top-part. Просьба по аналогии поправить и везде ниже

2022-06-27 15:40 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.top-part__title,
.histogram__title  и тд

2022-06-27 15:40 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.chart {
.histogram__chart

2022-06-27 15:40 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    gap: 2px;
1px

2022-06-27 15:40 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    margin: 40px 0 24px 0;
паддинг есть на уровне блока, точно нужен марджин снизу?

2022-06-27 15:45 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-06-28 19:34 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.chart {
любой класс элемента или модификатора начинается с имени блока - так мы даем понять, что речь идет о его составных частях. Поэтому - .histogram__chart-column / .histogram__column

2022-06-29 11:50 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-29 16:07 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-29 16:17 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-07-05 10:37 UTC, klyukinaxen commented on 04-lection2/01-histogram/histogram.css
> +@import '../../assets/fonts/fonts.css';
тут поправила

2022-07-05 11:00 UTC, GSemikozov approved these changes

2022-07-12 10:22 UTC, merged